package com.example.superstoresimulator.domain.metrics

import com.example.superstoresimulator.domain.Money
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.json.Json

private val json = Json { ignoreUnknownKeys = true }

fun DailyMetrics.toEntity(): ArchivedDailyMetricsEntity = ArchivedDailyMetricsEntity(
    dayNumber = dayNumber,
    dayOfWeek = dayOfWeek,
    subtotalCents = subtotal.cents,
    taxCollectedCents = taxCollected.cents,
    transactionsCompleted = transactionsCompleted,
    rentPaidCents = rentPaid.cents,
    wagesPaidCents = wagesPaid.cents,
    refundsProcessed = refundsProcessed,
    refundAmountCents = refundAmount.cents,
    customersServed = customersServed,
    itemsSold = itemsSold,
    itemsStocked = itemsStocked,
    itemsOrdered = itemsOrdered,
    lostRevenueCents = lostRevenue.cents,
    itemsLostToOutOfStock = itemsLostToOutOfStock,
    itemsExpired = itemsExpired,
    expiredWasteCostCents = expiredWasteCost.cents,
    avgCashierUtilization = avgCashierUtilization,
    avgStockerUtilization = avgStockerUtilization,
    avgFreshUtilization = avgFreshUtilization,
    avgZoneScore = avgZoneScore,
    markdownsSavedCents = markdownsSaved.cents,
    markupExtraRevenueCents = markupExtraRevenue.cents,
    itemsMarkedDown = itemsMarkedDown,
    vendorCommissionPaidCents = vendorCommissionPaid.cents,
    vendorItemsSold = vendorItemsSold,
    vendorRevenueCents = vendorRevenue.cents,
    soldItemEventsJson = json.encodeToString(ListSerializer(SoldItemEvent.serializer()), soldItemEvents),
    outOfStockEventsJson = json.encodeToString(ListSerializer(OutOfStockEvent.serializer()), outOfStockEvents),
    expiredItemEventsJson = json.encodeToString(ListSerializer(ExpiredItemEvent.serializer()), expiredItemEvents),
    autoOrderedFreshItemsJson = json.encodeToString(ListSerializer(AutoOrderLineItem.serializer()), autoOrderedFreshItems),
    incompleteOrderedFreshItemsJson = json.encodeToString(ListSerializer(IncompleteAutoOrderLineItem.serializer()), incompleteOrderedFreshItems),
    autoOrderedNormalItemsJson = json.encodeToString(ListSerializer(AutoOrderLineItem.serializer()), autoOrderedNormalItems),
    incompleteOrderedNormalItemsJson = json.encodeToString(ListSerializer(IncompleteAutoOrderLineItem.serializer()), incompleteOrderedNormalItems),
    deliveredTrucksJson = json.encodeToString(ListSerializer(DeliveredTruckRecord.serializer()), deliveredTrucks),
    autoHireEventsJson = json.encodeToString(ListSerializer(AutoHireEvent.serializer()), autoHireEvents),
)

fun ArchivedDailyMetricsEntity.toDailyMetrics(): DailyMetrics = DailyMetrics(
    dayNumber = dayNumber,
    dayOfWeek = dayOfWeek,
    subtotal = Money(subtotalCents),
    taxCollected = Money(taxCollectedCents),
    transactionsCompleted = transactionsCompleted,
    rentPaid = Money(rentPaidCents),
    wagesPaid = Money(wagesPaidCents),
    refundsProcessed = refundsProcessed,
    refundAmount = Money(refundAmountCents),
    customersServed = customersServed,
    itemsSold = itemsSold,
    itemsStocked = itemsStocked,
    itemsOrdered = itemsOrdered,
    lostRevenue = Money(lostRevenueCents),
    itemsLostToOutOfStock = itemsLostToOutOfStock,
    itemsExpired = itemsExpired,
    expiredWasteCost = Money(expiredWasteCostCents),
    avgCashierUtilization = avgCashierUtilization,
    avgStockerUtilization = avgStockerUtilization,
    avgFreshUtilization = avgFreshUtilization,
    avgZoneScore = avgZoneScore,
    markdownsSaved = Money(markdownsSavedCents),
    markupExtraRevenue = Money(markupExtraRevenueCents),
    itemsMarkedDown = itemsMarkedDown,
    vendorCommissionPaid = Money(vendorCommissionPaidCents),
    vendorItemsSold = vendorItemsSold,
    vendorRevenue = Money(vendorRevenueCents),
    soldItemEvents = json.decodeFromString(ListSerializer(SoldItemEvent.serializer()), soldItemEventsJson),
    outOfStockEvents = json.decodeFromString(ListSerializer(OutOfStockEvent.serializer()), outOfStockEventsJson),
    expiredItemEvents = json.decodeFromString(ListSerializer(ExpiredItemEvent.serializer()), expiredItemEventsJson),
    autoOrderedFreshItems = json.decodeFromString(ListSerializer(AutoOrderLineItem.serializer()), autoOrderedFreshItemsJson),
    incompleteOrderedFreshItems = json.decodeFromString(ListSerializer(IncompleteAutoOrderLineItem.serializer()), incompleteOrderedFreshItemsJson),
    autoOrderedNormalItems = json.decodeFromString(ListSerializer(AutoOrderLineItem.serializer()), autoOrderedNormalItemsJson),
    incompleteOrderedNormalItems = json.decodeFromString(ListSerializer(IncompleteAutoOrderLineItem.serializer()), incompleteOrderedNormalItemsJson),
    deliveredTrucks = json.decodeFromString(ListSerializer(DeliveredTruckRecord.serializer()), deliveredTrucksJson),
    autoHireEvents = json.decodeFromString(ListSerializer(AutoHireEvent.serializer()), autoHireEventsJson),
)

fun ArchivedDailyMetricsSummary.toDailyMetrics(): DailyMetrics = DailyMetrics(
    dayNumber = dayNumber,
    dayOfWeek = dayOfWeek,
    subtotal = Money(subtotalCents),
    taxCollected = Money(taxCollectedCents),
    transactionsCompleted = transactionsCompleted,
    rentPaid = Money(rentPaidCents),
    wagesPaid = Money(wagesPaidCents),
    refundsProcessed = refundsProcessed,
    refundAmount = Money(refundAmountCents),
    customersServed = customersServed,
    itemsSold = itemsSold,
    itemsStocked = itemsStocked,
    itemsOrdered = itemsOrdered,
    lostRevenue = Money(lostRevenueCents),
    itemsLostToOutOfStock = itemsLostToOutOfStock,
    itemsExpired = itemsExpired,
    expiredWasteCost = Money(expiredWasteCostCents),
    avgCashierUtilization = avgCashierUtilization,
    avgStockerUtilization = avgStockerUtilization,
    avgFreshUtilization = avgFreshUtilization,
    avgZoneScore = avgZoneScore,
    markdownsSaved = Money(markdownsSavedCents),
    markupExtraRevenue = Money(markupExtraRevenueCents),
    itemsMarkedDown = itemsMarkedDown,
    vendorCommissionPaid = Money(vendorCommissionPaidCents),
    vendorItemsSold = vendorItemsSold,
    vendorRevenue = Money(vendorRevenueCents),
)
